model_type: CNNLSTM 
model_class: CNNLSTMForecaster
trainer_class: CNNLSTMTrainer
params:
  input_len: 64
  input_size: 1672
  output_len: 5     # lag=[1,2,3,4] so the maximum prediction lag = 4 + 1 = 5 
  output_size: 424  # output_size = num_target
  hidden_size: 128
  num_layers: 2
  batch_size: 16
  dropout: 0.1
  channels: 128
  kernel_size: 5
  num_conv_layers: 2
optimizer: Adam
lr: 0.001
epochs: 50
lr_policy: constant
patience: 5