model:
  model_type: DERITS
  trainer_class: DERTrainer
  params:
    batch_size: 32 
    output_len: 5
    input_size: 1671
    output_size: 424
    amp: true 
    val_ratio: 0.2 
    num_workers: 4 
    #orders: [0, 1, 2]  # Default orders
  search_space:
    orders: {type: categorical, choices: ["012", "01", "12", "02"]}
    rnn_hidden_mul: {type: int, choices: [1, 2]}
    input_len:   {type: int,   low: 128, high: 512, step: 64}
    depth:       {type: int,   low: 1, high: 4, step: 1}
    kernel_size: {type: categorical, choices: [3, 5, 7]}
    dropout:     {type: float, low: 0.0, high: 0.3, step: 0.1}
    band_l1:     {type: float, low: 1e-6, high: 1e-2, log: true}
    hf_weight:   {type: float, low: 1e-6, high: 1e-3, log: true}
    hf_fraction: {type: float, low: 0.05, high: 0.3, step: 0.05}
    grad_clip:   {type: float, low: 0.1, high: 5.0, step: 0.5}
epochs: 25
  