model_type: TCN
model_class: TCNForecaster
trainer_class: TCNTrainer
params:
  input_len: 64
  input_size: 1672
  output_len: 1
  num_targets: 20
  hidden_size: 128
  num_layers: 2
  batch_size: 16
  dropout: 0.1
  channels: 128
  blocks: 3
  tcn_kernel: 3
optimizer: Adam
lr: 0.001
epochs: 5
lr_policy: constant
patience: 3